### PR TITLE
vendoring with Godep + Go 1.6 vendoring

### LINKED ISSUE #11: Godep is not up to date
@iwanbk can you please make sure all the dependencies are properly vendored in Godep and that we can build the project using only godep libs please.

### PR DESCRIPTION
**Pull request by iwanbk**
fix #11

More about godep + vendoring https://github.com/tools/godep#migrating-to-vendor

### CODE REVIEW

**Comment by muhamadazmy** [comment]
We don't need to add the entire libraries in the repo, I am totally against this. Please just update the godep file to reflect the libraries version used.

I reject this pull request.

**Comment by iwanbk** [comment]
@muhamadazmy 

the real advantage of vendoring (copying all libs source code) is it provides  guarantee that these libs will exists when we need it, consider these:
- lib repo disappear or moved to somewhere else
- lib repo server is down.

please also consider these:
- Go developers recommends to use vendoring
https://groups.google.com/forum/m/#!topic/golang-dev/nMWoEAG55v8

- read this blog post https://blog.gopheracademy.com/advent-2015/vendor-folder/
 snippet : 
```
Projects that cared about not breaking when their dependent packages changed or went away did one of the following
```

- the way this repo use Godep is not following the godep creator. Godep already created a `.gitignore` file in `Godeps/_workspace/.gitignore`, `Godeps/_workspace/src` is not in that file. But this repo ignored it by modifying .gitignore

**Comment by muhamadazmy** [comment]
@iwanbk 
I'm personally against vendoring. IMHO if the code disappeared from the internet, we really should not use it anymore. I totally understand your points. But I totally hate having all the dependencies packed in the repo.

Anyway, it's not my decision alone, can @zaibon @grimpy tell what they think about this ?

**Comment by zaibon** [comment]
I personally think we should consider vendoring as it's  recommended by the Go community.
It's maybe not "sexy" to have all the libs in the repo of the projects itself. But I really don't want us to face a "left-pad incident". Having a fully self contained repo is IMO totally acceptable.

**Comment by robvanmieghem** [comment]
+1 for vendoring, is not only about deletion of other projects, is also when someone can access a dependent library and can inject code in ours this way.

Either it should be `go gettable` like open source libraries or be vendored according to go practices when it's a product imho.

**Comment by zaibon** [comment]
@iwanbk Can you make sure the build on travis pass please. 
Then I'll merge it. thanks

**Comment by iwanbk** [comment]
@zaibon sorry for this inconvenience.
I just found that github.com/kothar/brotli-go still failing it's test for Go 1.6.

So, our choices are:
1. fixing github.com/kothar/brotli-go test for Go 1.6
2. Back to Go 1.5

Our master branch passed travis because it doesn't execute `go test` against vendored packages.

**Comment by iwanbk** [comment]
@zaibon
latest brotli already compatible with Go 1.6.

But not sure why,  there are many missed packages in this PR.  I will create another PR.

**Pull request closed without merging**
